'use client';

import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Bell, BellOff, Check, ClipboardCheck, Clock3, Crown, FileDown, ListPlus, Minus, Pencil, Plus, ReceiptText, RotateCcw, Settings2, Sparkles, Target, Trash2, Wrench } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger } from '@/components/ui/select';

const team = ['Макс', 'Алина', 'Алексей', 'Коля', 'Ксюша', 'Ира', 'Арсен'];
const tech = [
  { id: 'new', label: 'Apple · нова', personal: 80, online: 40 },
  { id: 'open', label: 'Apple · open box', personal: 120, online: 60 },
  { id: 'used', label: 'Apple · вживана', personal: 160, online: 80 },
  { id: 'periphery', label: 'Периферія', personal: 50, online: 25 },
  { id: 'other', label: 'Техніка · інше', personal: 80, online: 40 },
];
const accessories = [
  { id: 'glass', label: 'Скло і плівки', rates: [8, 9, 10] },
  { id: 'small', label: 'До 1 000 грн', rates: [10, 12, 14] },
  { id: 'middle', label: '1 001–3 000 грн', rates: [3, 5, 7] },
  { id: 'large', label: 'Від 3 001 грн', rates: [2, 3, 4] },
  { id: 'original', label: 'Apple original', rates: [2, 3, 4] },
];
const bonuses = [
  { id: 'google', label: 'Відгук Google', short: 'G', value: 100 },
  { id: 'hotline', label: 'Hotline / Instagram', short: 'H', value: 300 },
  { id: 'hire', label: 'Рекомендація людини', short: '+', value: 4000 },
];
const servicePlans = [
  { value: 'basic', label: 'Базовий · 20%', rate: 20 },
  { value: 'plus', label: 'Понад план · 25%', rate: 25 },
  { value: 'pro', label: 'Понад план + · 30%', rate: 30 },
  { value: 'max', label: 'Понад план ++ · 35%', rate: 35 },
];
type Values = Record<string, number>;
type DailyReport = { id: string; employee: string; date: string; base: number; tech: number; accessories: number; services: number; serviceUnits: number; repairs: number; focus: number; bonuses: number; total: number; units: number; turnover: number; approaches: number };
type QueueState = { queue: string[]; approachCounts: Record<string, number>; notificationsEnabled: boolean };
type Mood = 'low' | 'okay' | 'great';
type MoodState = { moods: Record<string, Mood>; counts: Record<Mood, number> };
type CalculatorDraft = { employee?: string; dayRate?: number; days?: number; plan?: string; servicePlan?: string; techCount?: Values; accessorySums?: Values; serviceAmount?: number; serviceCount?: number; repairProfit?: number; focusPay?: number; bonusCount?: Values };
const moodOptions: { value: Mood; emoji: string; label: string }[] = [{ value: 'low', emoji: '😕', label: 'Поганий' }, { value: 'okay', emoji: '🙂', label: 'Середній' }, { value: 'great', emoji: '🤩', label: 'Відмінний' }];
const money = (value: number) => new Intl.NumberFormat('uk-UA', { style: 'currency', currency: 'UAH', maximumFractionDigits: 0 }).format(value);
const telegramSafe = (value: string) => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const emptyTech = () => Object.fromEntries(tech.flatMap(x => [[`${x.id}-personal`, 0], [`${x.id}-online`, 0]]));
const emptyAccessories = () => Object.fromEntries(accessories.map(x => [x.id, 0]));
const emptyBonuses = () => Object.fromEntries(bonuses.map(x => [x.id, 0]));

function Picker({ value, onChange, options, label }: { value: string; onChange: (value: string) => void; options: { value: string; label: string }[]; label: string }) {
  const selectedLabel = options.find(option => option.value === value)?.label ?? value;
  return <Select value={value} onValueChange={nextValue => { if (nextValue) onChange(nextValue); }}><SelectTrigger aria-label={label} className="h-11 w-full rounded-xl border-0 bg-[#edf0f5] px-4 text-sm font-semibold text-[#3c424c]"><span className="min-w-0 flex-1 truncate text-left">{selectedLabel}</span></SelectTrigger><SelectContent className="cyber-select-content">{options.map(x => <SelectItem className="cyber-select-item" key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>;
}

function Stepper({ value, onChange, compact = false }: { value: number; onChange: (value: number) => void; compact?: boolean }) {
  return <div className={`cyber-stepper flex items-center justify-between rounded-xl ${compact ? 'px-2 py-1.5' : 'px-3 py-2'}`}><button aria-label="Зменшити" onClick={() => onChange(Math.max(0, value - 1))} className="cyber-stepper-control grid size-7 place-items-center rounded-lg"><Minus className="size-4" /></button><span className="cyber-stepper-value min-w-7 text-center text-base font-black">{value}</span><button aria-label="Збільшити" onClick={() => onChange(value + 1)} className="cyber-stepper-control grid size-7 place-items-center rounded-lg"><Plus className="size-4" /></button></div>;
}

function AmountField({ value, onChange, placeholder }: { value: number; onChange: (value: number) => void; placeholder: string }) {
  return <div className="relative"><Input inputMode="numeric" value={value || ''} onChange={e => onChange(Number(e.target.value.replace(/\D/g, '')) || 0)} placeholder={placeholder} className="h-11 rounded-xl border-0 bg-[#edf0f5] pr-11 text-right text-base font-bold shadow-none placeholder:text-[#9ba2af] focus-visible:ring-2" /><span className="pointer-events-none absolute right-4 top-2.5 text-sm font-semibold text-[#8a92a0]">грн</span></div>;
}

export default function Home() {
  const [view, setView] = useState<'calculator' | 'leaders' | 'randomizer'>('calculator');
  const [employee, setEmployee] = useState('Макс');
  const [dayRate, setDayRate] = useState(500);
  const [days, setDays] = useState(0);
  const [plan, setPlan] = useState('under');
  const [servicePlan, setServicePlan] = useState('basic');
  const [techCount, setTechCount] = useState<Values>(emptyTech);
  const [accessorySums, setAccessorySums] = useState<Values>(emptyAccessories);
  const [serviceAmount, setServiceAmount] = useState(0);
  const [serviceCount, setServiceCount] = useState(0);
  const [repairProfit, setRepairProfit] = useState(0);
  const [focusPay, setFocusPay] = useState(0);
  const [bonusCount, setBonusCount] = useState<Values>(emptyBonuses);
  const [reports, setReports] = useState<DailyReport[]>([]);
  const [queue, setQueue] = useState<string[]>(team);
  const [approachCounts, setApproachCounts] = useState<Record<string, number>>({});
  const [moods, setMoods] = useState<Record<string, Mood>>({});
  const [moodCounts, setMoodCounts] = useState<Record<Mood, number>>({ low: 0, okay: 0, great: 0 });
  const [moodSaving, setMoodSaving] = useState(false);
  const [notificationsEnabled, setNotificationsEnabled] = useState(true);
  const [newQueueName, setNewQueueName] = useState('');
  const [queueSaving, setQueueSaving] = useState(false);
  const [editingEmployee, setEditingEmployee] = useState(false);
  const [customEmployee, setCustomEmployee] = useState('');
  const [saved, setSaved] = useState(false);
  const [sending, setSending] = useState(false);
  const [sendMessage, setSendMessage] = useState('');
  const [loaded, setLoaded] = useState(false);
  const [draftLoaded, setDraftLoaded] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [dayText, setDayText] = useState('Сьогодні');
  useEffect(() => { const cached = localStorage.getItem('motiva-reports'); if (cached) setReports(JSON.parse(cached)); setLoaded(true); fetch('/api/reports').then(response => response.ok ? response.json() : []).then(remote => { if (Array.isArray(remote) && remote.length) setReports(remote as DailyReport[]); }).catch(() => {}); fetch('/api/queue').then(response => response.ok ? response.json() : null).then(data => { const queueData = data as QueueState | null; if (queueData?.queue?.length) setQueue(queueData.queue); if (queueData?.approachCounts) setApproachCounts(queueData.approachCounts); if (typeof queueData?.notificationsEnabled === 'boolean') setNotificationsEnabled(queueData.notificationsEnabled); }).catch(() => {}); fetch('/api/moods').then(response => response.ok ? response.json() : null).then(data => { const moodData = data as MoodState | null; if (moodData?.moods) setMoods(moodData.moods); if (moodData?.counts) setMoodCounts(moodData.counts); }).catch(() => {}); }, []);
  useEffect(() => { if (loaded) localStorage.setItem('motiva-reports', JSON.stringify(reports)); }, [loaded, reports]);
  useEffect(() => { try { const raw = localStorage.getItem('ipeople-pulse-draft'); if (!raw) return; const draft = JSON.parse(raw) as CalculatorDraft; if (typeof draft.employee === 'string') setEmployee(draft.employee); if (typeof draft.dayRate === 'number') setDayRate(draft.dayRate); if (typeof draft.days === 'number') setDays(draft.days); if (typeof draft.plan === 'string') setPlan(draft.plan); if (typeof draft.servicePlan === 'string') setServicePlan(draft.servicePlan); if (draft.techCount) setTechCount({ ...emptyTech(), ...draft.techCount }); if (draft.accessorySums) setAccessorySums({ ...emptyAccessories(), ...draft.accessorySums }); if (typeof draft.serviceAmount === 'number') setServiceAmount(draft.serviceAmount); if (typeof draft.serviceCount === 'number') setServiceCount(draft.serviceCount); if (typeof draft.repairProfit === 'number') setRepairProfit(draft.repairProfit); if (typeof draft.focusPay === 'number') setFocusPay(draft.focusPay); if (draft.bonusCount) setBonusCount({ ...emptyBonuses(), ...draft.bonusCount }); } catch { /* A damaged device draft is safely ignored. */ } finally { setDraftLoaded(true); } }, []);
  useEffect(() => { if (!draftLoaded) return; localStorage.setItem('ipeople-pulse-draft', JSON.stringify({ employee, dayRate, days, plan, servicePlan, techCount, accessorySums, serviceAmount, serviceCount, repairProfit, focusPay, bonusCount } satisfies CalculatorDraft)); }, [accessorySums, bonusCount, dayRate, days, draftLoaded, employee, focusPay, plan, repairProfit, serviceAmount, serviceCount, servicePlan, techCount]);
  useEffect(() => { setDayText(new Intl.DateTimeFormat('uk-UA', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())); }, []);
  useEffect(() => { setHydrated(true); }, []);
  const planIndex = plan === 'under' ? 0 : plan === 'target' ? 1 : 2;
  const serviceRate = servicePlans.find(item => item.value === servicePlan)?.rate ?? 20;
  const calculations = useMemo(() => {
    const base = dayRate * days;
    const techPay = tech.reduce((sum, item) => sum + techCount[`${item.id}-personal`] * item.personal + techCount[`${item.id}-online`] * item.online, 0);
    const accessoriesPay = accessories.reduce((sum, item) => sum + Math.round(accessorySums[item.id] * item.rates[planIndex] / 100), 0);
    const servicesPay = Math.round(serviceAmount * serviceRate / 100);
    const repairsPay = Math.round(repairProfit * 0.05);
    const bonusPay = bonuses.reduce((sum, item) => sum + bonusCount[item.id] * item.value, 0);
    const units = Object.values(techCount).reduce((sum, count) => sum + count, 0);
    const turnover = Object.values(accessorySums).reduce((sum, amount) => sum + amount, 0) + serviceAmount + repairProfit;
    return { base, techPay, accessoriesPay, servicesPay, repairsPay, focusPay, bonusPay, units, turnover, total: base + techPay + accessoriesPay + servicesPay + repairsPay + focusPay + bonusPay };
  }, [accessorySums, bonusCount, dayRate, days, focusPay, planIndex, repairProfit, serviceAmount, serviceRate, techCount]);
  function changeCount(key: string, value: number, target: 'tech' | 'bonus') { if (target === 'tech') setTechCount(current => ({ ...current, [key]: value })); else setBonusCount(current => ({ ...current, [key]: value })); setSaved(false); }
  function resetShift() { setDayRate(500); setDays(0); setPlan('under'); setServicePlan('basic'); setTechCount(emptyTech()); setAccessorySums(emptyAccessories()); setServiceAmount(0); setServiceCount(0); setRepairProfit(0); setFocusPay(0); setBonusCount(emptyBonuses()); setSaved(false); setSendMessage(''); }
  async function selectMood(mood: Mood) { if (moodSaving) return; setMoodSaving(true); try { const response = await fetch('/api/moods', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ employee, mood }) }); const data = await response.json().catch(() => ({})) as Partial<MoodState> & { error?: string }; if (!response.ok) throw new Error(data.error || 'mood-failed'); if (data.moods) setMoods(data.moods); if (data.counts) setMoodCounts(data.counts); } catch (error) { window.alert(error instanceof Error && error.message !== 'mood-failed' ? error.message : 'Не вдалося зберегти настрій. Спробуйте ще раз.'); } finally { setMoodSaving(false); } }
  async function persistQueue(nextQueue = queue, nextNotifications = notificationsEnabled) {
    setQueueSaving(true);
    try {
      const response = await fetch('/api/queue', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ queue: nextQueue, notificationsEnabled: nextNotifications }) });
      const result = await response.json().catch(() => ({})) as Partial<QueueState> & { error?: string };
      if (!response.ok) throw new Error(result.error || 'save-failed');
      setQueue(result.queue?.length ? result.queue : nextQueue);
      setNotificationsEnabled(typeof result.notificationsEnabled === 'boolean' ? result.notificationsEnabled : nextNotifications);
    } catch (error) {
      window.alert(error instanceof Error && error.message !== 'save-failed' ? error.message : 'Не вдалося зберегти чергу. Спробуйте ще раз.');
    } finally { setQueueSaving(false); }
  }
  async function shuffleQueue() { const next = [...queue]; for (let index = next.length - 1; index > 0; index -= 1) { const target = Math.floor(Math.random() * (index + 1)); [next[index], next[target]] = [next[target], next[index]]; } setQueue(next); await persistQueue(next); }
  async function saveCustomEmployee() { const name = customEmployee.trim().slice(0, 80); if (!name) { window.alert('Впишіть ім’я співробітника.'); return; } const existing = queue.find(item => item.toLocaleLowerCase() === name.toLocaleLowerCase()); if (existing) { setEmployee(existing); setEditingEmployee(false); return; } const nextQueue = [...queue, name]; setEmployee(name); setQueue(nextQueue); await persistQueue(nextQueue); setEditingEmployee(false); }
  function renameQueueMember(index: number, name: string) { setQueue(current => current.map((item, currentIndex) => currentIndex === index ? name : item)); }
  function addQueueMember() { const name = newQueueName.trim(); if (!name) return; if (queue.some(item => item.toLocaleLowerCase() === name.toLocaleLowerCase())) { window.alert('Ця людина вже є у черзі.'); return; } setQueue(current => [...current, name]); setNewQueueName(''); }
  function removeQueueMember(index: number) { if (queue.length === 1) { window.alert('У черзі має залишитися хоча б одна людина.'); return; } setQueue(current => current.filter((_, currentIndex) => currentIndex !== index)); }
  async function updateNotifications(next: boolean) { setNotificationsEnabled(next); await persistQueue(queue, next); }
  async function markApproach() {
    const current = queue[0];
    if (!current || queueSaving) return;
    setQueueSaving(true);
    try {
      const markResponse = await fetch('/api/queue', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ employee: current }) });
      const mark = await markResponse.json().catch(() => ({})) as { count?: number; error?: string };
      if (!markResponse.ok) throw new Error(mark.error || 'mark-failed');
      const nextQueue = [...queue.slice(1), current];
      const saveResponse = await fetch('/api/queue', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ queue: nextQueue, notificationsEnabled }) });
      const savedQueue = await saveResponse.json().catch(() => ({})) as Partial<QueueState> & { error?: string };
      if (!saveResponse.ok) throw new Error(savedQueue.error || 'save-failed');
      setApproachCounts(counts => ({ ...counts, [current]: Number(mark.count ?? (counts[current] ?? 0) + 1) }));
      setQueue(savedQueue.queue?.length ? savedQueue.queue : nextQueue);
    } catch (error) {
      window.alert(error instanceof Error && error.message !== 'mark-failed' && error.message !== 'save-failed' ? error.message : 'Не вдалося зберегти підхід. Спробуйте ще раз.');
    } finally { setQueueSaving(false); }
  }
  async function resetLeaders() { if (!window.confirm('Очистити таблицю лідерів? Усі звіти команди буде видалено.')) return; try { const response = await fetch('/api/reports', { method: 'DELETE' }); if (!response.ok) throw new Error('clear-failed'); setReports([]); localStorage.removeItem('motiva-reports'); window.alert('Таблицю лідерів очищено.'); } catch { window.alert('Не вдалося очистити таблицю. Спробуйте ще раз.'); } }
  const reportText = useMemo(() => {
    const techRows = tech.flatMap(item => [
      techCount[`${item.id}-personal`] ? `• ${item.label}, особистий: ${techCount[`${item.id}-personal`]} шт. — ${money(techCount[`${item.id}-personal`] * item.personal)}` : '',
      techCount[`${item.id}-online`] ? `• ${item.label}, інтернет: ${techCount[`${item.id}-online`]} шт. — ${money(techCount[`${item.id}-online`] * item.online)}` : '',
    ]).filter(Boolean);
    const accessoryRows = accessories.map(item => accessorySums[item.id] ? `• ${item.label}: ${money(accessorySums[item.id])} → ${money(Math.round(accessorySums[item.id] * item.rates[planIndex] / 100))}` : '').filter(Boolean);
    return [`iPeople PULSE · звіт зміни`, `Дата: ${dayText}`, `Співробітник: ${employee}`, '', `Зміна: ${days} дн. — ${money(calculations.base)}`, `Гаджети: ${calculations.units} шт. — ${money(calculations.techPay)}`, ...techRows, `Послуги: ${serviceCount} шт. · ${money(serviceAmount)} → ${money(calculations.servicesPay)} (${serviceRate}%)`, `Аксесуари: ${money(Object.values(accessorySums).reduce((sum, value) => sum + value, 0))} → ${money(calculations.accessoriesPay)}`, ...accessoryRows, `Ремонти: ${money(repairProfit)} → ${money(calculations.repairsPay)} (5%)`, `Фокусний товар: ${money(focusPay)}`, `Підходи до клієнтів: ${approachCounts[employee] ?? 0}`, `Бонуси: ${money(calculations.bonusPay)}`, '', `В ЗП за зміну: ${money(calculations.total)}`].join('\n');
  }, [accessorySums, approachCounts, calculations, dayText, days, employee, focusPay, planIndex, repairProfit, serviceAmount, serviceCount, serviceRate, techCount]);
  const telegramText = useMemo(() => {
    const techRows = tech.flatMap(item => [
      techCount[`${item.id}-personal`] ? `• ${item.label} · особистий: <b>${techCount[`${item.id}-personal`]} шт.</b> · ${money(techCount[`${item.id}-personal`] * item.personal)}` : '',
      techCount[`${item.id}-online`] ? `• ${item.label} · інтернет: <b>${techCount[`${item.id}-online`]} шт.</b> · ${money(techCount[`${item.id}-online`] * item.online)}` : '',
    ]).filter(Boolean);
    const accessoryRows = accessories.map(item => accessorySums[item.id] ? `• ${item.label}: ${money(accessorySums[item.id])} → <b>${money(Math.round(accessorySums[item.id] * item.rates[planIndex] / 100))}</b>` : '').filter(Boolean);
    return [
      '✨ <b>iPeople PULSE</b>', '<i>ЗВІТ ЗМІНИ</i>', '━━━━━━━━━━━━━━',
      `📅 <b>${telegramSafe(dayText)}</b>`, `👤 Співробітник: <b>${telegramSafe(employee)}</b>`, '',
      '💼 <b>НАРАХУВАННЯ</b>', `🗓 Зміна: ${days} дн. · <b>${money(calculations.base)}</b>`,
      `📱 Гаджети: <b>${calculations.units} шт.</b> · ${money(calculations.techPay)}`, ...techRows,
      `🛠 Послуги: <b>${serviceCount} шт.</b> · ${money(serviceAmount)} → <b>${money(calculations.servicesPay)}</b> (${serviceRate}%)`,
      `🎧 Аксесуари: ${money(Object.values(accessorySums).reduce((sum, value) => sum + value, 0))} → <b>${money(calculations.accessoriesPay)}</b>`, ...accessoryRows,
      `🔧 Ремонти: ${money(repairProfit)} → <b>${money(calculations.repairsPay)}</b> (5%)`, `🎯 Фокусний товар: <b>${money(focusPay)}</b>`, `🎯 Підходи до клієнтів: <b>${approachCounts[employee] ?? 0}</b>`,
      `🎁 Бонуси: <b>${money(calculations.bonusPay)}</b>`, '', '━━━━━━━━━━━━━━',
      `💰 <b>В ЗП ЗА ЗМІНУ: ${money(calculations.total)}</b>`, '⚡ <i>iPeople PULSE · мотивація команди</i>',
    ].filter(Boolean).join('\n');
  }, [accessorySums, approachCounts, calculations, dayText, days, employee, focusPay, planIndex, repairProfit, serviceAmount, serviceCount, serviceRate, techCount]);
  function createReport(): DailyReport { const date = new Date().toISOString().slice(0, 10); return { id: `${Date.now()}-${Math.random().toString(36).slice(2)}`, employee, date, base: calculations.base, tech: calculations.techPay, accessories: calculations.accessoriesPay, services: calculations.servicesPay, serviceUnits: serviceCount, repairs: calculations.repairsPay, focus: calculations.focusPay, bonuses: calculations.bonusPay, total: calculations.total, units: calculations.units, turnover: calculations.turnover, approaches: approachCounts[employee] ?? 0 }; }
  function saveReport(report: DailyReport) { setReports(current => [...current, report]); setSaved(true); }
  async function sendReport() { setSending(true); setSendMessage(''); const details = createReport(); try { const response = await fetch('/api/reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ employee, date: details.date, total: calculations.total, text: reportText, telegramText, details }) }); const result = await response.json().catch(() => ({})) as { telegramReady?: boolean; error?: string }; if (!response.ok) throw new Error(result.error || 'send-failed'); try { saveReport(details); } catch { /* Telegram delivery must not depend on this device. */ } setSendMessage(result.telegramReady ? 'Звіт надіслано в Telegram.' : 'Звіт збережено, але Telegram тимчасово недоступний.'); } catch (error) { setSendMessage(error instanceof Error && error.message !== 'send-failed' ? error.message : 'Не вдалося надіслати звіт. Спробуйте ще раз.'); } finally { setSending(false); } }
  function createPdfReport() { const reportWindow = window.open('', '_blank', 'width=760,height=980'); if (!reportWindow) { setSendMessage('Дозвольте відкрити вікно PDF і спробуйте ще раз.'); return; } const safeText = reportText.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); reportWindow.document.write(`<!doctype html><html lang="uk"><head><meta charset="utf-8"><title>iPeople PULSE - ${employee}</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#101a2d;background:#fff}header{display:flex;align-items:center;gap:12px;border-bottom:3px solid #19dfe8;padding-bottom:16px;margin-bottom:20px}.mark{width:42px;height:42px;display:grid;place-items:center;border-radius:12px;color:#fff;font-weight:800;background:linear-gradient(135deg,#24dfea,#ff4fd8)}h1{font-size:22px;margin:0}p{margin:4px 0;color:#526077}pre{font-family:Arial,sans-serif;font-size:13px;line-height:1.65;white-space:pre-wrap}footer{position:fixed;bottom:0;font-size:10px;color:#74809a}</style></head><body><header><div class="mark">iP</div><div><h1>iPeople PULSE</h1><p>Звіт зміни</p></div></header><pre>${safeText}</pre><footer>iPeople PULSE · сформовано ${new Date().toLocaleString('uk-UA')}</footer></body></html>`); reportWindow.document.close(); window.setTimeout(() => { reportWindow.focus(); reportWindow.print(); }, 250); setSendMessage('Оберіть «Зберегти як PDF» у системному вікні.'); }
  const leaderboard = [...reports].sort((a, b) => b.total - a.total);
  if (!hydrated) return <main className="cyber-screen grid min-h-screen place-items-center p-6 text-center"><div><div className="cyber-logo mx-auto mb-4 grid size-12 place-items-center rounded-2xl text-xl font-extrabold">iP</div><p className="font-extrabold">Завантажуємо iPeople PULSE…</p></div></main>;
  return <main className="cyber-screen min-h-screen"><header className="cyber-header border-b backdrop-blur"><div className="mx-auto flex max-w-[1260px] items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><div className="cyber-logo grid size-10 place-items-center rounded-xl text-xs font-black tracking-tighter">iP</div><div><p className="font-extrabold tracking-tight">iPeople <span className="cyber-pulse">PULSE</span></p><MoodPicker value={moods[employee]} saving={moodSaving} onSelect={selectMood} /></div></div><nav className="cyber-nav flex rounded-xl p-1"><button onClick={() => setView('calculator')} className={`rounded-lg px-3 py-2 text-sm font-bold ${view === 'calculator' ? 'bg-white text-[#246bfd] shadow-sm' : 'text-[#7a8493]'}`}>Калькулятор</button><button onClick={() => setView('leaders')} className={`cyber-leaders-tab rounded-lg px-3 py-2 text-sm font-bold ${view === 'leaders' ? 'bg-white text-[#246bfd] shadow-sm' : 'text-[#7a8493]'}`}><Crown className="size-4" /> Лідери</button><button onClick={() => setView('randomizer')} className={`cyber-randomizer-tab rounded-lg px-3 py-2 text-sm font-bold ${view === 'randomizer' ? 'bg-white text-[#246bfd] shadow-sm' : 'text-[#7a8493]'}`}><Sparkles className="size-4" /> Черга</button></nav></div></header>
  <div className="mx-auto max-w-[1260px] px-5 py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="mb-1 text-sm font-bold text-[#526fff]">{dayText}</p><h1 className="text-3xl font-extrabold tracking-tight">{view === 'calculator' ? 'Моя мотивація' : view === 'leaders' ? 'Таблиця лідерів' : 'Рандомайзер черги'}</h1></div>{view === 'calculator' ? <button type="button" onClick={resetShift} className="cyber-reset" title="Скинути всі дані зміни" aria-label="Скинути всі дані зміни"><span className="reset-clock"><Clock3 /></span><RotateCcw className="reset-arrow" /></button> : view === 'leaders' ? <button type="button" onClick={resetLeaders} className="cyber-reset cyber-leaders-reset" title="Очистити таблицю лідерів" aria-label="Очистити таблицю лідерів"><span className="reset-clock"><Crown /></span><RotateCcw className="reset-arrow" /></button> : null}</div>
  {view === 'calculator' ? <div className="space-y-6"><section><h2 className="mb-3 text-xl font-extrabold">Основа</h2><div className="grid gap-3 rounded-3xl bg-[#e9ebf1] p-4 sm:grid-cols-2 lg:grid-cols-5"><Field label="Співробітник"><div className="flex gap-2">{editingEmployee ? <Input autoFocus value={customEmployee} onChange={event => setCustomEmployee(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') void saveCustomEmployee(); }} placeholder="Впишіть своє ім’я" className="h-11 rounded-xl border-0 bg-[#edf0f5] px-4 text-base font-bold text-[#3c424c] shadow-none placeholder:text-[#8a92a0]" /> : <Picker value={employee} onChange={setEmployee} label="Співробітник" options={queue.map(x => ({ value: x, label: x }))} />}<button type="button" disabled={queueSaving} onClick={() => { if (editingEmployee) void saveCustomEmployee(); else { setCustomEmployee(employee); setEditingEmployee(true); } }} className="cyber-person-edit grid size-11 shrink-0 place-items-center rounded-xl" title={editingEmployee ? 'Зберегти ім’я' : 'Вписати своє ім’я'} aria-label={editingEmployee ? 'Зберегти ім’я' : 'Вписати своє ім’я'}>{editingEmployee ? <Check className="size-5" /> : <Pencil className="size-4" />}</button></div></Field><Field label="Ставка за день"><AmountField value={dayRate} onChange={setDayRate} placeholder="0" /></Field><Field label="Відпрацьовані дні"><Stepper value={days} onChange={setDays} /></Field><Field label="План аксесуарів"><Picker value={plan} onChange={setPlan} label="План аксесуарів" options={[{ value: 'under', label: 'Базовий план' }, { value: 'target', label: '70–100% плану' }, { value: 'over', label: 'Понад 100% плану' }]} /></Field><Field label="План послуг"><Picker value={servicePlan} onChange={setServicePlan} label="План послуг" options={servicePlans} /></Field></div></section>
    <section><div className="mb-3 flex items-center gap-2"><h2 className="text-xl font-extrabold">Техніка</h2><span className="rounded-full bg-[#eaf0ff] px-2.5 py-1 text-xs font-bold text-[#3c5dcb]">кількість продажів</span></div><div className="grid gap-3 rounded-3xl bg-[#e9ebf1] p-4 sm:grid-cols-2 lg:grid-cols-5">{tech.map(item => <div key={item.id} className="rounded-2xl bg-white p-4 shadow-[0_3px_9px_rgb(23_30_45/0.04)]"><p className="min-h-10 text-sm font-extrabold">{item.label}</p><div className="mt-3 space-y-2"><div><p className="mb-1.5 text-xs font-bold text-[#7c8696]">Особистий · {item.personal} грн</p><Stepper compact value={techCount[`${item.id}-personal`]} onChange={value => changeCount(`${item.id}-personal`, value, 'tech')} /></div><div><p className="mb-1.5 text-xs font-bold text-[#7c8696]">Інтернет · {item.online} грн</p><Stepper compact value={techCount[`${item.id}-online`]} onChange={value => changeCount(`${item.id}-online`, value, 'tech')} /></div></div></div>)}</div></section>
    <section><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><h2 className="text-xl font-extrabold">Аксесуари</h2><span className="rounded-full bg-[#eaf0ff] px-2.5 py-1 text-xs font-bold text-[#3c5dcb]">введіть оборот за категоріями</span></div><p className="text-sm font-bold text-[#526fff]">Поточна ставка: {plan === 'under' ? 'базовий план' : plan === 'target' ? '70–100%' : 'понад 100%'}</p></div><div className="grid gap-3 rounded-3xl bg-[#e9ebf1] p-4 sm:grid-cols-2 lg:grid-cols-5">{accessories.map(item => <div key={item.id} className="rounded-2xl bg-white p-4"><p className="min-h-10 text-sm font-extrabold">{item.label}</p><p className="mb-3 text-xs font-bold text-[#6976a0]">{item.rates[planIndex]}% у зарплату</p><AmountField value={accessorySums[item.id]} onChange={value => { setAccessorySums(current => ({ ...current, [item.id]: value })); setSaved(false); }} placeholder="0" /></div>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl bg-[#e9ebf1] p-4"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white p-5"><h2 className="text-xl font-extrabold">Бонуси</h2><div className="mt-4 space-y-3">{bonuses.map(item => <div key={item.id} className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold">{item.label}</p><p className="text-xs text-[#798394]">{money(item.value)} за 1</p></div><Stepper compact value={bonusCount[item.id]} onChange={value => changeCount(item.id, value, 'bonus')} /></div>)}</div></div><ServiceCard amount={serviceAmount} count={serviceCount} rate={serviceRate} onChange={value => { setServiceAmount(value); setSaved(false); }} onCountChange={value => { setServiceCount(value); setSaved(false); }} /><div className="rounded-2xl bg-[#183458] p-5 text-white"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white/12"><Wrench className="size-5 text-[#8fb8ff]" /></div><div><h2 className="font-extrabold">Ремонти вручну</h2><p className="text-sm text-[#b9cae4]">Впишіть чистий прибуток з ремонтів</p></div></div><div className="mt-5"><label className="text-sm font-bold text-[#cfddf3]">Чистий прибуток з ремонтів</label><div className="relative mt-2"><Input inputMode="numeric" value={repairProfit || ''} onChange={e => { setRepairProfit(Number(e.target.value.replace(/\D/g, '')) || 0); setSaved(false); }} placeholder="0" className="h-14 rounded-xl border-0 bg-white px-4 pr-12 text-right text-xl font-extrabold text-[#1b202a]" /><span className="absolute right-4 top-4 text-sm font-bold text-[#778396]">грн</span></div></div><div className="mt-4 flex items-center justify-between border-t border-white/15 pt-4"><span className="text-sm font-semibold text-[#b9cae4]">5% у зарплату</span><span className="text-xl font-extrabold">{money(calculations.repairsPay)}</span></div></div></div><FocusCard value={focusPay} onChange={value => { setFocusPay(value); setSaved(false); }} /></div><Summary calculation={calculations} onSend={sendReport} onPdf={createPdfReport} sending={sending} sendMessage={sendMessage} /></section>
  </div> : view === 'leaders' ? <Leaders reports={leaderboard} moodCounts={moodCounts} /> : <QueueRandomizer queue={queue} approachCounts={approachCounts} notificationsEnabled={notificationsEnabled} newQueueName={newQueueName} queueSaving={queueSaving} onShuffle={shuffleQueue} onMarkApproach={markApproach} onSaveQueue={() => persistQueue()} onRename={renameQueueMember} onAdd={addQueueMember} onRemove={removeQueueMember} onNewQueueNameChange={setNewQueueName} onNotificationsChange={updateNotifications} />}</div></main>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-sm font-bold text-[#5b6472]"><span>{label}</span>{children}</label>; }
function MoodPicker({ value, saving, onSelect }: { value?: Mood; saving: boolean; onSelect: (mood: Mood) => void }) { return <div className="mood-picker" aria-label="Настрій за сьогодні">{moodOptions.map(option => <button key={option.value} type="button" disabled={saving} onClick={() => onSelect(option.value)} className={`mood-choice ${value === option.value ? 'mood-choice-active' : ''}`} title={option.label} aria-label={`Настрій: ${option.label}`} aria-pressed={value === option.value}><span>{option.emoji}</span><em>{option.label}</em></button>)}</div>; }
function ServiceCard({ amount, count, rate, onChange, onCountChange }: { amount: number; count: number; rate: number; onChange: (value: number) => void; onCountChange: (value: number) => void }) { const pay = Math.round(amount * rate / 100); return <div className="rounded-2xl bg-[#183458] p-5 text-white"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white/12"><Settings2 className="size-5 text-[#8fb8ff]" /></div><div><h2 className="font-extrabold">Послуги</h2><p className="text-sm text-[#b9cae4]">Впишіть суму послуг за зміну</p></div></div><div className="mt-5 grid gap-3"><label className="text-sm font-bold text-[#cfddf3]">Кількість послуг<Stepper compact value={count} onChange={onCountChange} /></label><label className="text-sm font-bold text-[#cfddf3]">Сума послуг<div className="relative mt-2"><Input inputMode="numeric" value={amount || ''} onChange={e => onChange(Number(e.target.value.replace(/\D/g, '')) || 0)} placeholder="0" className="h-14 rounded-xl border-0 bg-white px-4 pr-12 text-right text-xl font-extrabold text-[#1b202a]" /><span className="absolute right-4 top-4 text-sm font-bold text-[#778396]">грн</span></div></label></div><div className="mt-4 flex items-center justify-between border-t border-white/15 pt-4"><span className="text-sm font-semibold text-[#b9cae4]">{rate}% у зарплату</span><span className="text-xl font-extrabold">{money(pay)}</span></div></div>; }
function FocusCard({ value, onChange }: { value: number; onChange: (value: number) => void }) { return <div className="cyber-focus-card mt-4 rounded-2xl p-5 text-white"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-white/10"><Target className="size-5 text-[#e7b6ff]" /></div><div><h2 className="font-extrabold">Фокусний товар</h2><p className="text-sm text-[#d8b9e9]">Впишіть вручну чистий заробіток за товар</p></div></div><div className="mt-5"><label className="text-sm font-bold text-[#f0d9ff]">Нарахування в ЗП<div className="relative mt-2"><Input inputMode="numeric" value={value || ''} onChange={event => onChange(Number(event.target.value.replace(/\D/g, '')) || 0)} placeholder="0" className="h-14 rounded-xl border-0 bg-white px-4 pr-12 text-right text-xl font-extrabold text-[#1b202a]" /><span className="absolute right-4 top-4 text-sm font-bold text-[#778396]">грн</span></div></label></div><div className="mt-4 flex items-center justify-between border-t border-white/15 pt-4"><span className="text-sm font-semibold text-[#d8b9e9]">Додається одразу в зарплату</span><span className="text-xl font-extrabold">{money(value)}</span></div></div>; }
function Summary({ calculation, onSend, onPdf, sending, sendMessage }: { calculation: { base: number; techPay: number; accessoriesPay: number; servicesPay: number; repairsPay: number; focusPay: number; bonusPay: number; total: number }; onSend: () => void; onPdf: () => void; sending: boolean; sendMessage: string }) { const rows = [['Ставка', calculation.base], ['Техніка', calculation.techPay], ['Аксесуари', calculation.accessoriesPay], ['Послуги', calculation.servicesPay], ['Ремонти · 5%', calculation.repairsPay], ['Фокусний товар', calculation.focusPay], ['Бонуси', calculation.bonusPay]]; return <aside className="rounded-3xl bg-white p-6 shadow-[0_12px_35px_rgb(23_30_45/0.08)]"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-[#eaf0ff] text-[#246bfd]"><ReceiptText className="size-5" /></div><div><h2 className="font-extrabold">Підсумок зміни</h2><p className="text-sm text-[#7a8493]">Нарахування за сьогодні</p></div></div><div className="mt-5 space-y-3">{rows.map(([label, value]) => <div key={String(label)} className="flex justify-between text-sm"><span className="text-[#697483]">{label}</span><span className="font-bold">{money(Number(value))}</span></div>)}</div><div className="mt-5 border-t border-[#e8ebf1] pt-5"><p className="text-sm font-bold text-[#697483]">Разом до зарплати</p><p className="mt-1 text-4xl font-extrabold tracking-tight text-[#246bfd]">{money(calculation.total)}</p></div><Button disabled={sending} onClick={onSend} className="mt-6 h-11 w-full rounded-xl bg-[#246bfd] hover:bg-[#1759da]"><Check /> {sending ? 'Надсилаємо…' : 'Відправити звіт'}</Button>{sendMessage && <p className="mt-3 text-center text-sm font-semibold text-[#526fff]">{sendMessage}</p>}<Button variant="outline" onClick={onPdf} className="cyber-pdf mt-2 h-11 w-full rounded-xl"><FileDown /> Створити PDF-звіт</Button></aside>; }
function Leaders({ reports, moodCounts }: { reports: DailyReport[]; moodCounts: Record<Mood, number> }) { const best = reports[0]; return <div className="space-y-6"><section className="grid gap-4 sm:grid-cols-3"><Stat tone="crown" icon={<Crown />} label="Лідер за зарплатою" value={best?.employee ?? '—'} /><Stat tone="chart" icon={<BarChart3 />} label="Звітів за сьогодні" value={String(reports.length)} /><Stat tone="reports" icon={<ClipboardCheck />} label="Нараховано команді" value={money(reports.reduce((sum, x) => sum + x.total, 0))} /></section><TeamMood moodCounts={moodCounts} /><section className="overflow-hidden rounded-3xl border border-[#e2e6ee] bg-white shadow-[0_10px_30px_rgb(23_30_45/0.04)]"><div className="px-6 py-5"><h2 className="text-xl font-extrabold">Мотиваційна таблиця</h2><p className="mt-1 text-sm text-[#7a8493]">Кожен зберігає свій підсумок наприкінці зміни.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-[#f4f6f9] text-xs uppercase tracking-wide text-[#778292]"><tr><th className="px-6 py-3">Місце</th><th className="px-4 py-3">Співробітник</th><th className="px-4 py-3 text-right">Техніка, шт</th><th className="px-4 py-3 text-right">Ремонти</th><th className="px-6 py-3 text-right">Нараховано</th></tr></thead><tbody>{reports.length ? reports.map((report, index) => <tr key={report.id} className="border-t border-[#edf0f4]"><td className="px-6 py-5 font-extrabold text-[#526fff]">#{index + 1}</td><td className="px-4 py-5 font-extrabold">{report.employee}</td><td className="px-4 py-5 text-right">{report.units}</td><td className="px-4 py-5 text-right">{money(report.repairs)}</td><td className="px-6 py-5 text-right font-extrabold text-[#246bfd]">{money(report.total)}</td></tr>) : <tr><td colSpan={5} className="px-6 py-12 text-center text-[#7a8493]">Ще немає збережених звітів.</td></tr>}</tbody></table></div></section></div>; }
function TeamMood({ moodCounts }: { moodCounts: Record<Mood, number> }) { const total = moodCounts.low + moodCounts.okay + moodCounts.great; const score = total ? (moodCounts.low + moodCounts.okay * 2 + moodCounts.great * 3) / total : 0; const state = !total ? 'Ще немає оцінок' : score < 1.67 ? 'Поганий' : score < 2.34 ? 'Середній' : 'Відмінний'; const max = Math.max(1, moodCounts.low, moodCounts.okay, moodCounts.great); return <section className="team-mood rounded-3xl p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold text-[#75f7ff]">Сьогодні</p><h2 className="mt-1 text-xl font-extrabold">Настрій команди</h2><p className="mt-1 text-sm text-[#8fa7bc]">Кожен обирає один настрій за свою зміну.</p></div><div className="mood-status"><span>{total ? '⚡' : '○'}</span><b>{state}</b><small>{total} {total === 1 ? 'голос' : 'голосів'}</small></div></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{moodOptions.map(option => <div key={option.value} className={`mood-bar mood-bar-${option.value}`}><div className="flex items-center justify-between gap-3"><span className="text-2xl">{option.emoji}</span><strong>{moodCounts[option.value]}</strong></div><p>{option.label}</p><div className="mood-track"><i style={{ width: `${Math.max(0, moodCounts[option.value] / max * 100)}%` }} /></div></div>)}</div></section>; }
function QueueRandomizer({ queue, approachCounts, notificationsEnabled, newQueueName, queueSaving, onShuffle, onMarkApproach, onSaveQueue, onRename, onAdd, onRemove, onNewQueueNameChange, onNotificationsChange }: { queue: string[]; approachCounts: Record<string, number>; notificationsEnabled: boolean; newQueueName: string; queueSaving: boolean; onShuffle: () => void; onMarkApproach: () => void; onSaveQueue: () => void; onRename: (index: number, value: string) => void; onAdd: () => void; onRemove: (index: number) => void; onNewQueueNameChange: (value: string) => void; onNotificationsChange: (value: boolean) => void }) {
  const next = queue[0];
  return <section className="cyber-queue rounded-3xl border border-[#e2e6ee] bg-white p-5 sm:p-8">
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
      <div className="cyber-queue-next rounded-3xl p-5 sm:p-6">
        <div className="flex items-start gap-3"><div className="cyber-queue-icon grid size-11 shrink-0 place-items-center rounded-2xl"><Clock3 className="size-5" /></div><div><p className="text-sm font-bold text-[#8ea4bd]">Наступний у черзі</p><h2 className="mt-1 text-3xl font-black tracking-tight">{next ?? 'Черга порожня'}</h2><p className="mt-2 text-sm text-[#a8b9cf]">Після відмітки людина автоматично переходить у кінець списку.</p></div></div>
        <Button disabled={!next || queueSaving} onClick={onMarkApproach} className="cyber-queue-button mt-6 h-12 w-full rounded-xl"><Check /> {queueSaving ? 'Зберігаємо…' : 'Позначити підхід до клієнта'}</Button>
      </div>
      <div className="cyber-queue-notification rounded-3xl p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/10 text-[#3deaf1]">{notificationsEnabled ? <Bell className="size-5" /> : <BellOff className="size-5" />}</div><div><h2 className="font-extrabold">Оповіщення в Telegram</h2><p className="mt-1 text-sm text-[#a8b9cf]">Надсилати повідомлення після кожного підходу.</p></div></div><button type="button" aria-pressed={notificationsEnabled} aria-label="Увімкнути або вимкнути оповіщення" onClick={() => onNotificationsChange(!notificationsEnabled)} disabled={queueSaving} className={`cyber-toggle ${notificationsEnabled ? 'cyber-toggle-on' : ''}`}><span /></button></div><p className="mt-6 text-xs font-bold tracking-wide text-[#6d86a5]">{notificationsEnabled ? 'УВІМКНЕНО · АДМІН ОТРИМУЄ ПОВІДОМЛЕННЯ' : 'ВИМКНЕНО · ВІДМІТКИ ЛИШАЮТЬСЯ У ЧЕРЗІ'}</p></div>
    </div>
    <div className="mt-6 rounded-3xl border border-[#17466a] bg-[#07182d]/75 p-4 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-extrabold">Список черги</h2><p className="mt-1 text-sm text-[#8ea4bd]">Відредагуйте команду та збережіть один спільний порядок для всіх.</p></div><Button disabled={queueSaving} onClick={onSaveQueue} variant="outline" className="cyber-queue-save h-11 rounded-xl"><ClipboardCheck /> {queueSaving ? 'Зберігаємо…' : 'Зберегти список'}</Button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{queue.map((name, index) => <div key={`${name}-${index}`} className={`cyber-queue-editor flex items-center gap-3 rounded-2xl p-3 ${index === 0 ? 'cyber-queue-first' : ''}`}><span className="grid size-8 shrink-0 place-items-center rounded-lg text-sm font-black">{index + 1}</span><Input value={name} onChange={event => onRename(index, event.target.value)} aria-label={`Співробітник у черзі №${index + 1}`} className="h-10 border-0 bg-transparent px-1 font-extrabold text-white shadow-none focus-visible:ring-0" /><span className="hidden whitespace-nowrap text-xs font-bold text-[#4ee6ee] sm:inline">{approachCounts[name] ?? 0} підходів</span><button type="button" onClick={() => onRemove(index)} aria-label={`Прибрати ${name} з черги`} className="grid size-9 shrink-0 place-items-center rounded-xl text-[#8ea4bd] transition hover:bg-[#2a1645] hover:text-[#ff70d9]"><Trash2 className="size-4" /></button></div>)}</div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Input value={newQueueName} onChange={event => onNewQueueNameChange(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') onAdd(); }} placeholder="Додати співробітника до черги" className="h-11 rounded-xl border border-[#17466a] bg-[#061426] px-4 font-semibold text-white placeholder:text-[#68809d]" /><Button onClick={onAdd} variant="outline" className="cyber-queue-save h-11 shrink-0 rounded-xl"><ListPlus /> Додати</Button></div></div>
    <div className="mt-6 flex flex-col gap-5 rounded-3xl border border-[#2b1d59] bg-[linear-gradient(110deg,#10184a,#37113e)] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-2xl bg-[#f2b94b]/15 text-[#ffd35a]"><Sparkles className="size-5" /></div><div><h2 className="text-xl font-extrabold">Чесний рандомайзер на ранок</h2><p className="mt-1 text-sm text-[#bcaed3]">Визначте стартовий порядок перед початком зміни — без ручного вибору.</p></div></div><Button disabled={queueSaving || queue.length < 2} onClick={onShuffle} className="cyber-queue-button h-12 shrink-0 rounded-xl px-5"><Sparkles /> Чесно перемішати</Button></div>
  </section>;
}
function Stat({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: 'crown' | 'chart' | 'reports' }) { return <div className={`cyber-stat cyber-stat-${tone} rounded-3xl border border-[#e2e6ee] bg-white p-5`}><div className="cyber-stat-icon grid size-10 place-items-center rounded-xl bg-[#eaf0ff] text-[#246bfd]">{icon}</div><p className="mt-5 text-sm font-bold text-[#7a8493]">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></div>; }
